### ISSUE TITLE
Figuring out how to contribute

### ISSUE THREAD

**Issue by Magicpastry** [jackastner/android-fooddeserts#1]
I've actually never contributed to another person's github project before, so it will take about an hour for me to figure out what the heck I should be doing. In the meantime, I'll try and make a group chat with groupme, though if you guys would prefer discord or anything else let me know.

**Comment by john-h-kastner** [comment]
I added you as a collaborator so you should be able to push to it like it's your own repo once you accept the invite. AndroidStudio should take care of most of the git stuff if you look under the VCS tab on the toolbar.
